server:
  port: 9091

spring:
  application:
    name: Product Microservices
  data:
    mongodb:
      host: localhost
      port: 27017
      database: shopping
  profiles:
    active: local

logging:
  file:
    name: d:\logs\product.log
  logback:
    rollingpolicy:
      max-file-size: 50KB
#  level:
#    root: TRACE
#    path: d:\logs #spring.log

product:
  currencies:
    - VND
    - USD
    - EUR

---
server:
  port: 9094

spring:
  config:
    activate:
      on-profile:
        - prod

