server:
  port: 9091

spring:
  application:
    name: Product Microservices
  data:
    mongodb:
      host: localhost
      port: 27017
      database: shopping
  profiles:
    active: local
  boot:
    admin:
      client:
        url:
          - http://localhost:8081

logging:
  file:
    name: d:\logs\product.log
#    path: d:\logs #spring.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
  level:
    root: INFO

# actuator specific
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
  endpoint:
    health:
      show-details: always
  health:
    mongo:
      enabled: true
  info:
    env:
      enabled: true

product:
  currencies:
    - VND
    - USD
    - EUR

info:
  app:
    name: Product Microservices
    version: 1.0
    description: Add and retrieve product information

---
server:
  port: 9094

spring:
  config:
    activate:
      on-profile:
        - prod

