server:
  port: 9091

spring:
  application:
    name: Product Microservices
  data:
    mongodb:
      host: localhost
      port: 27017
      database: shopping
#  profiles:
#    active: dev, prod

product:
  currencies:
    - VND
    - USD
    - EUR

---
server:
  port: 9094

spring:
  config:
    activate:
      on-profile:
        - prod

