server:
  port: 8081

spring:
  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: 618764dff1d7d4
    password: 577668734abdfe
    test-connection: true
  boot:
    admin:
      ui:
        brand: "<img scr='assets/img/logo.png'><span>BQN</span>"
        title: 'BQN Learning'
        login-icon: 'assets/img/logo.png'
        available-languages:
          - en
          - fr
        view-settings:
          - name: 'about'
            enabled: false
      notify:
        mail:
          to:
            - quocbinh0612@gmail.com
